CREATE USER 'virtuestream'@'localhost' IDENTIFIED BY 'virtuestream';

GRANT ALL PRIVILEGES ON * . * TO 'virtuestream'@'localhost';

CREATE DATABASE  IF NOT EXISTS `virtuestream`;
USE `virtuestream`;

CREATE TABLE `virtuestream`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customername` VARCHAR(200) NOT NULL,
  `gatestatus` SMALLINT(2) NULL,
  `rid` VARCHAR(45) NULL,
  `dc1` VARCHAR(45) NULL,
  `dc2` VARCHAR(45) NULL,
  `startdate` DATE NULL,
  `completepercent` VARCHAR(45) NULL,
  `pm1` VARCHAR(45) NULL,
  `pm2` VARCHAR(45) NULL,
  `owner` VARCHAR(45) NULL,
  `coeengineer1` VARCHAR(45) NULL,
  `coeengineer2` VARCHAR(45) NULL,
  `vmcount` INT NULL,
  `vmcompletecount` INT NULL,
  `status` VARCHAR(45) NULL,
  `amstransition` VARCHAR(4) NULL,
  `outstanding` VARCHAR(1500) NULL,
  `issues` VARCHAR(1000) NULL,
  `sapbasis` VARCHAR(45) NULL,
  `deploymethod` VARCHAR(45) NULL
  PRIMARY KEY (`id`));

INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Almaviva ARCA GOMMA',6,'TN2J','NLDC','FRDC',SYSDATE(),'0.4','Max','','Karthik','Raghavendra','',11,6,'Incomplete','NO','Phase -2 Handed over to PM. ','','N/A');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Iron Mountain',6,'A0LM','AUDC1','AUDC2',SYSDATE(),'0.7','Alberto','','Kiran','Subhash','Raghavendra',350,187,'Incomplete','NO','Next schedule on 23rd August (8 VM s) , Project moved till Sep 20th.','','N/A');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('REPSOL TALISMAN ',6,'TN4H','USDC3','USDC4',SYSDATE(),'0.8','Gayathri','Gayathri','Kiran','Subhash','',28,14,'Incomplete','NO','4 Vm s migrated successfully on 13th, We have more 2 VM s in PROD scheduled on 10th August.','','N/A');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Almaviva ARCA MERCI',6,'TN2J','NLDC','FRDC',SYSDATE(),'0.4','Vivek','','Dion','Ajay','',15,2,'Incomplete','NO','A few VMs have already been deployed and awaiting confirmation from PM for the remainder. QAS has been completed.','','N/A');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('SAP HEC DEWA',6,'TN4K','Moro','Warsaw',SYSDATE(),'0.6','Cameron','','Dion','Ajay','Deepesh',289,150,'Incomplete','NO','Pre-PRD with Basis - PRD and SAP CR and DR oustanding','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('SAP HEC TNT',6,'TN4U','NLDC','FRDC',SYSDATE(),'0.6','Cameron','','Dion','Sekar','Pinaki',134,18,'Incomplete','NO','pHANA migration pending. Migration from VEC to HEC pending.','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('HEC SHARED TNT FRUN NLDC1',6,'TN4T','NLDC','FRDC',SYSDATE(),'0.9','Cameron','','Dion','Subhash','',6,6,'Incomplete','NO','VMs and storage renamed to match RID. Network layer to be renamed, scheduled for 25th.','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Aramex',6,'RBFI','UKDC','NLDC',SYSDATE(),'0.7','Jay','','Kiran','Ajay','Deepesh',52,29,'Incomplete','NO','20 PROD VM s are planned to deliver this week. Started deploying VM;s.','','N/A');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('ICTSI',6,'TN51','AUDC1','AUDC2',SYSDATE(),'0.5','Jeff','','Sanjay','Kiran','Deepesh',60,40,'Incomplete','NO','Mock for v2v was completed last weekend for ICTSI. Vulnabarities issues with servere is been discussed with sec ops now.','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Technip FMC',6,'A0LL','FRDC1','NLDC1',SYSDATE(),'0.7','Karen Hall','','Bob','Subhash','Raghavendra',139,108,'Incomplete','NO','The migration cutover of the remaining 32 TechnipFMC Production systems has been scheduled for August 16-18.   
There are 32 VMs being migrated to FRDC1 in this V2V cutover.  
15 VMs with SAP Basis Support. 
3 VMs with Oracle DBs, 3 VMs with SQL Server DBs & 1 vHANA server.  
The 6 VMs with Oracle & SQL Server DBs all require Vormetric encryption.','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('ENOC',6,'TN4Y','UAE01','UAE02',SYSDATE(),'0.8','Sefoora','Ranjak','Dion','Ajay','',36,36,'Incomplete','NO','Stage2 DEV systems handed over to Basis team, backups and monitoring work in progress. Sap router network connectivity is still pending','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('GE Healthcare',6,'A0N1','USDC04','USDC03',SYSDATE(),'0.1','Jay','','Dion','Karthik','',56,16,'Incomplete','NO','1st Phase completed with Basis. Awating file system details for other boxes. Infra structure service is pending ','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Omron',6,'TN4Z','JPDC1','JPDC2',SYSDATE(),'1','Aphurvika','','Sanjay','Kiran','Deepesh',6,6,'Incomplete','NO','Omrom Migration was completed last weekend. VMs are handed over to customer for further validation.','','N/A');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('GE Steam',6,'A0MZ','USDC3','USDC4',SYSDATE(),'0.4','Kamal','','Karthik','Manjunath','Deepesh',80,35,'Incomplete','NO','All boxes are with the basis team. Awaiting for the scan report','','BASIS Support');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Almaviva - TN2J - TPM-POC',6,'TN2J','NL01','UK01',SYSDATE(),'0.4','Max','','Karthik','Manjunath','Deepesh',41,8,'Incomplete','NO','Intial phase 1 & 2 servers handed over to the customer, except the sql boxes as we are awaiting the customer info. Network and vlan need to change on all the boxes.','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('TNT DR ',6,'TN52','UKDC1','',SYSDATE(),'0','Jay','','Karthik','Manjunath','',8,0,'Incomplete','NO','Awaiting solution to get finalised','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('TNT Java Split',6,'TN522','NLDC1','',SYSDATE(),'0','Jay','','Karthik','Manjunath','',0,0,'Incomplete','NO','Awaiting solution to get finalised','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Schenck',2,'TN53','DEDC01','',SYSDATE(),'0.9','Max','','Japin','Muneer','Pinaki',4,4,'Incomplete','NO','Handover to customer. DPO Team waiting netowork issue to be fixed to finish the backup setup in DE03 [Secondary DC ]','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Deloitte ABB',6,'TN51','FRDC01','NLDC01',SYSDATE(),'0.5','Cameron','','Japin','Jay','Pinaki',10,10,'Incomplete','NO','Storage in place awaiting networks','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('SBD',6,'A0HJ','USDC4','',SYSDATE(),'0','Vivek','','Kevin','Raghavendra','Pinaki',14,14,'Incomplete','NO','Customer Postponed to October ','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Elanco',6,'A0N5','MNSS','EGVG',SYSDATE(),'0','','','Ben/Prasad','Muneer','Jay',0,0,'Incomplete','NO','Awaiting for CPT','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('Veolia',6,'TN55','AUDC1','AUDC2',SYSDATE(),'0.3','Sanjay Kaler','','Subhash ','Raghavendra','',21,0,'Incomplete','NO','Dev VM Build is in progress, Dev VM s will be delivered to VS Basis team','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('GE Grid ',0,'A0JY','USDC04','USDC03',SYSDATE(),'','Gayathri','','Karthik','Manjunath','',6,3,'','',' 5 / 6 vms  need to confirmed by the PM. 3 Jump hosts are delivered. Issue is ongoing wit hthe Storage requirement','','');
INSERT INTO `virtuestream`.`customer` (`customername`, `gatestatus`, `rid`, `dc1`,`dc2`, `startdate`, `completepercent`, `pm1`, `pm2`, `owner`, `coeengineer1`, `coeengineer2`, `vmcount`, `vmcompletecount`, `status`, `amstransition`, `outstanding`, `issues`, `sapbasis`) VALUES ('FYFFES(Next Phase)',7,'TN4W','NLDC/UKDC','FRDC',SYSDATE(),'1','Alex','','Karthik','Manjunath','Kiran',8,0,'Complete','NO','Gate 7 remediations done.','','BASIS Support');

Commit;